### ISSUE TITLE
Create a comparison with Restify and other frameworks

### ISSUE THREAD

**Issue by FlavioBrognara** [fearlessjs/fearless#1]

**Comment by rodrigooler** [comment]
@FlavioBrognara as soon as the release is okay in version 0.1.0 I will elaborate a benchmark with some frameworks such as Express, Koa, Fastify, Restify, Micro and Hapi. The focus of the benchmark will be performance with many requirements and connections.

Once you have everything ready, I'll put the details in this issue.
